### ISSUE TITLE
Clean up old releases

### ISSUE THREAD

**Issue by xel1045** [eXolnet/deployer#7]

**Comment by tomzx** [comment]
Already done. See https://github.com/eXolnet/deployer/blob/master/deployer.php#L114-L122

**Comment by xel1045** [comment]
Well, I think that a command should be run to clean up old releases. Otherwise, you don't have any backup of previous releases.

**Comment by tomzx** [comment]
I'm not sure what you mean. We're only deleting old releases at the end of a newly installed release. In the configuration, we specify how many releases we want to keep.

So, for example, we install 5 releases. They are all kept since we have configured the script to save up to 5 of them. When we install a new release, at the end of the script we remove the oldest release so that we still have 5 releases on the server.

If we need to rollback we would simply need to update the `current` symlink to point to the previous release (up to 3 more rollback being possible).

Does that make sense?

Otherwise, what would be the purpose of the clean command (since release management is somewhat automated by this procedure)?

**Comment by xel1045** [comment]
Oh! I misread the code. I was thinking that old releases were deleted on every deploys.
